trigger: none
pr: none

variables:
  - group: novu-deploy-vars

stages:

- stage: NovuHelmDeploy
  displayName: "Novu Helm Deploy"

  jobs:
    - deployment: NovuHelmJob
      displayName: "Helm Deploy Novu"

      environment:
        name: 'k8s-production'
        resourceType: VirtualMachine

      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                fetchDepth: '0'

              - script: |
                  helm upgrade --install novu-release \
                    $(Build.SourcesDirectory)/novu_deployment/helm/deployments \
                    --namespace $(K8S_NAMESPACE) \
                    --create-namespace \
                    --atomic \
                    --timeout 15m \
                    --debug \
                    --set namespace=$(K8S_NAMESPACE) \
                    --set mongo.url=$(MONGO_URL) \
                    --set redis.url=$(REDIS_URL) \
                    --set redis.host=$(REDIS_HOST) \
                    --set redis.password=$(REDIS_PASSWORD) \
                    --set auth.jwtSecret=$(JWT_SECRET) \
                    --set auth.encryptionKey=$(ENCRYPTION_KEY) \
                    --set auth.novuSecretKey=$(NOVU_SECRET_KEY) \
                    --set urls.apiRoot=$(API_ROOT) \
                    --set urls.stepResolverDispatchUrl=$(API_ROOT) \
                    --set urls.frontBase=$(FRONT_BASE) \
                    --set urls.wsUrl=$(WS_URL) \
                    --set env.corsOrigin=$(CORS_ORIGIN)

                  kubectl get pods -n $(K8S_NAMESPACE)

                displayName: "Helm Upgrade - Novu"