namespace: dev

image:
  pullPolicy: Always

api:
  name: novu-api
  image: ghcr.io/novuhq/novu/api
  tag: "3.15.0"
  replicaCount: 1

dashboard:
  name: novu-dashboard
  image: ghcr.io/novuhq/novu/dashboard
  tag: "3.15.0"
  replicaCount: 1

worker:
  name: novu-worker
  image: ghcr.io/novuhq/novu/worker
  tag: "3.15.0"
  replicaCount: 1

ws:
  name: novu-ws
  image: ghcr.io/novuhq/novu/ws
  tag: "3.15.0"
  replicaCount: 1

mongo:
  url: "$(MONGO_URL)"

redis:
  url: "$(REDIS_URL)"
  host: "$(REDIS_HOST)"
  port: "6379"
  password: "$(REDIS_PASSWORD)"

auth:
  jwtSecret: "$(JWT_SECRET)"
  encryptionKey: "$(ENCRYPTION_KEY)"
  novuSecretKey: "$(NOVU_SECRET_KEY)"

urls:
  apiRoot: "$(API_ROOT)"
  frontBase: "$(FRONT_BASE)"
  wsUrl: "$(WS_URL)"
  stepResolverDispatchUrl: "$(API_ROOT)"

env:
  nodeEnv: "production"
  disableTelemetry: "true"
  loggingLevel: "info"
  corsOrigin: "$(CORS_ORIGIN)"