apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: {{ .Values.env.nodeEnv | quote }}
            - name: PORT
              value: "3000"
            - name: DISABLE_TELEMETRY
              value: {{ .Values.env.disableTelemetry | quote }}
            - name: MONGO_URL
              value: {{ .Values.mongo.url | quote }}
            - name: REDIS_URL
              value: {{ .Values.redis.url | quote }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
            - name: REDIS_CACHE_SERVICE_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_CACHE_SERVICE_PORT
              value: {{ .Values.redis.port | quote }}
            - name: JWT_SECRET
              value: {{ .Values.auth.jwtSecret | quote }}
            - name: STORE_ENCRYPTION_KEY
              value: {{ .Values.auth.encryptionKey | quote }}
            - name: API_ROOT_URL
              value: {{ .Values.urls.apiRoot | quote }}
            - name: FRONT_BASE_URL
              value: {{ .Values.urls.frontBase | quote }}
            - name: CORS_ORIGIN
              value: {{ .Values.env.corsOrigin | quote }}
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: STORAGE_SERVICE
              value: "LOCAL"
            - name: IS_API_EE_ENABLED
              value: "false"
            - name: NEW_RELIC_ENABLED
              value: "false"
            - name: NEW_RELIC_APP_NAME
              value: "novu-api"
            - name: SENTRY_DSN
              value: ""
            - name: LAUNCH_DARKLY_SDK_KEY
              value: ""
            - name: NODE_OPTIONS
              value: "--max-http-header-size=16384"
            - name: STEP_RESOLVER_DISPATCH_URL
              value: {{ .Values.urls.stepResolverDispatchUrl | quote }}
            - name: NOVU_SECRET_KEY
              value: {{ .Values.auth.novuSecretKey | quote }}