apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ws.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ws.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ws.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ws.name }}
    spec:
      containers:
        - name: {{ .Values.ws.name }}
          image: "{{ .Values.ws.image }}:{{ .Values.ws.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: {{ .Values.env.nodeEnv | quote }}
            - name: PORT
              value: "3002"
            - name: DISABLE_TELEMETRY
              value: {{ .Values.env.disableTelemetry | quote }}
            - name: MONGO_URL
              value: {{ .Values.mongo.url | quote }}
            - name: REDIS_URL
              value: {{ .Values.redis.url | quote }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
            - name: JWT_SECRET
              value: {{ .Values.auth.jwtSecret | quote }}
            - name: STORE_ENCRYPTION_KEY
              value: {{ .Values.auth.encryptionKey | quote }}
            - name: WS_URL
              value: {{ .Values.urls.wsUrl | quote }}
            - name: API_ROOT_URL
              value: "http://{{ .Values.api.name }}.{{ .Values.namespace }}.svc.cluster.local:3000"
            - name: FRONT_BASE_URL
              value: {{ .Values.urls.frontBase | quote }}